import type { Incident } from '../domain/incident'; import type { ServiceGraph } from '../graph/serviceGraph';
export type CorrelationSignalType = 'same_service' | 'shared_dependency' | 'graph_path' | 'temporal_overlap' | 'shared_deployment' | 'matching_error_signature';
export type CorrelationStatus = 'observed' | 'correlated' | 'hypothesis' | 'supported' | 'confirmed';
export type CorrelationSignal = { type: CorrelationSignalType; value: string; strength: number; source: string };
export type IncidentCorrelation = { incident_a: string; incident_b: string; signals: CorrelationSignal[]; status: CorrelationStatus; explanation: string };
export type RootCauseCandidate = { candidate: string; status: 'hypothesis' | 'supported' | 'rejected' | 'confirmed'; score: number; supporting_incident_ids: string[]; supporting_evidence_ids: string[]; contradicting_evidence_ids: string[]; explanation: string };
export type IncidentGroup = { id: string; member_incident_ids: string[]; status: 'hypothesis' | 'supported'; reason: string };
const time = (incident: Incident) => Date.parse(incident.detected_at);
const deployment = (incident: Incident) => incident.evidence.find(item => item.kind === 'deployment');
const signature = (incident: Incident) => incident.evidence.find(item => item.kind === 'log')?.data['error_signature']?.toString();
export function correlateIncidents(a: Incident, b: Incident, graph: ServiceGraph, windowMs = 10 * 60 * 1000): IncidentCorrelation | undefined { if (a.id === b.id) return undefined; const signals: CorrelationSignal[] = []; if (a.service === b.service) signals.push({ type: 'same_service', value: a.service, strength: 1, source: 'incident' }); const aDeps = new Set(graph.getDependencies(a.service).map(node => node.id)); const shared = graph.getDependencies(b.service).map(node => node.id).filter(id => aDeps.has(id)); for (const dependency of shared) signals.push({ type: 'shared_dependency', value: dependency, strength: 0.8, source: 'service_graph' }); if (graph.findPath(a.service, b.service) || graph.findPath(b.service, a.service)) signals.push({ type: 'graph_path', value: `${a.service}<->${b.service}`, strength: 0.5, source: 'service_graph' }); if (Math.abs(time(a) - time(b)) <= windowMs) signals.push({ type: 'temporal_overlap', value: `${Math.abs(time(a) - time(b))}ms`, strength: 0.7, source: 'incident_timestamps' }); const da = deployment(a); const db = deployment(b); if (da && db && JSON.stringify(da.data) === JSON.stringify(db.data)) signals.push({ type: 'shared_deployment', value: da.summary, strength: 0.8, source: 'deployment_evidence' }); const sa = signature(a); if (sa && sa === signature(b)) signals.push({ type: 'matching_error_signature', value: sa, strength: 0.7, source: 'log_evidence' }); if (!signals.length) return undefined; const status: CorrelationStatus = signals.some(signal => signal.type === 'same_service' || signal.type === 'matching_error_signature') ? 'correlated' : 'hypothesis'; return { incident_a: a.id, incident_b: b.id, signals, status, explanation: `These incidents are ${status} based on ${signals.map(signal => signal.type).join(', ')}. Correlation is not confirmed causation.` }; }
export function findRootCauseCandidates(incidents: Incident[], graph: ServiceGraph): RootCauseCandidate[] { const candidates = new Map<string, RootCauseCandidate>(); for (const incident of incidents) for (const node of graph.getDependencies(incident.service)) { const current = candidates.get(node.id) ?? { candidate: node.id, status: 'hypothesis', score: 0, supporting_incident_ids: [], supporting_evidence_ids: [], contradicting_evidence_ids: [], explanation: 'Shared graph dependency is contextual evidence only.' }; current.score += 1; current.supporting_incident_ids.push(incident.id); current.supporting_evidence_ids.push(...incident.evidence.filter(item => item.kind === 'health' || item.kind === 'metric').map(item => item.id)); candidates.set(node.id, current); } return [...candidates.values()].map(candidate => ({ ...candidate, score: Math.min(1, candidate.score / Math.max(1, incidents.length)), status: candidate.supporting_evidence_ids.length > 0 ? 'supported' : 'hypothesis' })); }
export function groupCorrelatedIncidents(incidents: Incident[], graph: ServiceGraph): IncidentGroup | undefined { const correlations = incidents.flatMap((a, index) => incidents.slice(index + 1).map(b => correlateIncidents(a, b, graph)).filter((value): value is IncidentCorrelation => value !== undefined)); if (!correlations.length) return undefined; return { id: `group-${incidents.map(incident => incident.id).sort().join('-')}`, member_incident_ids: incidents.map(incident => incident.id), status: correlations.some(item => item.status === 'correlated') ? 'supported' : 'hypothesis', reason: correlations.map(item => item.explanation).join(' ') }; }
