import { z } from '@hono/zod-openapi';
import { createRequire } from 'node:module';
import { assertExecutionTransition, ResolveXExecutionStateSchema, type ResolveXExecutionState } from '../domain/execution';
const require = createRequire(import.meta.url);
export const ToolExecutionRecordSchema = z.object({ tool_call_id: z.string().min(1), tool_name: z.string().min(1), started_at: z.string(), completed_at: z.string().optional(), status: z.enum(['started', 'succeeded', 'failed', 'unknown']), approval_required: z.boolean(), approval_decision: z.enum(['allow', 'deny']).optional(), result: z.record(z.string(), z.unknown()).optional(), error: z.string().optional() });
export type ToolExecutionRecord = z.infer<typeof ToolExecutionRecordSchema>;
export const ResolveXExecutionRecordSchema = z.object({ execution_id: z.string().min(1), incident_id: z.string().min(1), tenant_id: z.string().min(1), agent_thread_id: z.string().optional(), status: ResolveXExecutionStateSchema, started_at: z.string(), updated_at: z.string(), current_step: z.string().optional(), last_completed_step: z.string().optional(), pending_approval: z.object({ tool_call_id: z.string(), tool_name: z.string(), requested_at: z.string(), risk: z.string() }).optional(), tool_executions: z.array(ToolExecutionRecordSchema), verification_attempts: z.number().int().min(0), attempt: z.number().int().min(0), error: z.string().optional() });
export type ResolveXExecutionRecord = z.infer<typeof ResolveXExecutionRecordSchema>;
export interface ExecutionStore { create(record: ResolveXExecutionRecord): Promise<ResolveXExecutionRecord>; get(id: string): Promise<ResolveXExecutionRecord | undefined>; listByIncident(incidentId: string, tenantId: string): Promise<ResolveXExecutionRecord[]>; transition(id: string, to: ResolveXExecutionState, patch?: Partial<ResolveXExecutionRecord>): Promise<ResolveXExecutionRecord>; recordTool(id: string, tool: ToolExecutionRecord): Promise<ResolveXExecutionRecord>; findCompletedTool(id: string, toolCallId: string): Promise<ToolExecutionRecord | undefined>; }
export function createPersistentExecutionStore(filePath: string): ExecutionStore { const fs = require('node:fs') as typeof import('node:fs'); const path = require('node:path') as typeof import('node:path'); const load = (): Map<string, ResolveXExecutionRecord> => { try { const raw = JSON.parse(fs.readFileSync(filePath, 'utf8')) as unknown; if (!Array.isArray(raw)) throw new Error('ResolveX execution store is malformed: expected an array'); const records = raw.map(item => ResolveXExecutionRecordSchema.parse(item)); return new Map(records.map(item => [item.execution_id, item])); } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return new Map(); throw error; } }; const save = (map: Map<string, ResolveXExecutionRecord>) => { fs.mkdirSync(path.dirname(filePath), { recursive: true }); const tmp = `${filePath}.tmp`; fs.writeFileSync(tmp, JSON.stringify([...map.values()])); fs.renameSync(tmp, filePath); }; const mutate = (id: string, fn: (record: ResolveXExecutionRecord) => void) => { const map = load(); const record = map.get(id); if (!record) throw new Error(`Execution not found: ${id}`); fn(record); record.updated_at = new Date().toISOString(); const parsed = ResolveXExecutionRecordSchema.parse(record); map.set(id, parsed); save(map); return structuredClone(parsed); }; return { async create(record) { const map = load(); if (map.has(record.execution_id)) throw new Error(`Execution already exists: ${record.execution_id}`); const parsed = ResolveXExecutionRecordSchema.parse(record); map.set(parsed.execution_id, parsed); save(map); return structuredClone(parsed); }, async get(id) { const record = load().get(id); return record ? structuredClone(record) : undefined; }, async listByIncident(incidentId, tenantId) { return [...load().values()].filter(item => item.incident_id === incidentId && item.tenant_id === tenantId).map(structuredClone); }, async transition(id, to, patch = {}) { return mutate(id, record => { assertExecutionTransition(record.status, to); Object.assign(record, patch, { status: to }); }); }, async recordTool(id, tool) { return mutate(id, record => { const existing = record.tool_executions.find(item => item.tool_call_id === tool.tool_call_id && item.status === 'succeeded'); if (existing) return; record.tool_executions.push(tool); }); }, async findCompletedTool(id, toolCallId) { return load().get(id)?.tool_executions.find(item => item.tool_call_id === toolCallId && item.status === 'succeeded'); } }; }
