export type GraphNodeKind = 'service' | 'database' | 'cache' | 'queue' | 'deployment' | 'repository' | 'external_api' | 'infrastructure';
export type GraphRelation = 'depends_on' | 'calls' | 'stores_data_in' | 'publishes_to' | 'consumes_from' | 'deployed_by' | 'owned_by' | 'affects' | 'caused_by';
export type GraphNode = { id: string; name: string; kind: GraphNodeKind; metadata: Record<string, unknown> };
export type GraphEdge = { from: string; to: string; relation: GraphRelation; metadata: Record<string, unknown> };
export type RelevantGraphNode = GraphNode & { distance: number; reason: string };
export interface ServiceGraph { addNode(node: GraphNode): void; addEdge(edge: GraphEdge): void; getNode(id: string): GraphNode | undefined; getNeighbors(id: string, relation?: GraphRelation): GraphNode[]; getDependencies(id: string): GraphNode[]; getDependents(id: string): GraphNode[]; findPath(from: string, to: string): string[] | undefined; relevantTo(id: string, depth?: number): RelevantGraphNode[]; nodes(): GraphNode[]; edges(): GraphEdge[]; }
export function createServiceGraph(initialNodes: GraphNode[] = [], initialEdges: GraphEdge[] = []): ServiceGraph {
  const nodes = new Map(initialNodes.map(node => [node.id, node])); const edges = [...initialEdges];
  const outgoing = (id: string, relation?: GraphRelation) => edges.filter(edge => edge.from === id && (!relation || edge.relation === relation)).map(edge => nodes.get(edge.to)).filter((node): node is GraphNode => !!node);
  return { addNode: node => void nodes.set(node.id, node), addEdge: edge => { if (!nodes.has(edge.from) || !nodes.has(edge.to)) throw new Error('Graph edge references unknown node'); edges.push(edge); }, getNode: id => nodes.get(id), getNeighbors: outgoing, getDependencies: id => outgoing(id, 'depends_on'), getDependents: id => edges.filter(e => e.to === id && e.relation === 'depends_on').map(e => nodes.get(e.from)).filter((n): n is GraphNode => !!n), findPath(from, to) { const q = [[from]]; const seen = new Set([from]); while (q.length) { const path = q.shift()!; if (path.at(-1) === to) return path; for (const n of outgoing(path.at(-1)!)) if (!seen.has(n.id)) { seen.add(n.id); q.push([...path, n.id]); } } return undefined; }, relevantTo(id, depth = 2) { const out: RelevantGraphNode[] = []; const q: Array<[string, number]> = [[id, 0]]; const seen = new Set([id]); while (q.length) { const [current, distance] = q.shift()!; if (distance) { const node = nodes.get(current); if (node) out.push({ ...node, distance, reason: `Connected to ${id} through the dependency graph` }); } if (distance >= depth) continue; for (const n of outgoing(current)) if (!seen.has(n.id)) { seen.add(n.id); q.push([n.id, distance + 1]); } } return out; }, nodes: () => [...nodes.values()], edges: () => [...edges] };
}
export function createDemoServiceGraph(): ServiceGraph { const g = createServiceGraph([['payment-api','Payment API','service'],['postgresql','PostgreSQL','database'],['redis','Redis','cache'],['payment-worker','Payment Worker','service'],['deployment-1.8.4','Deployment 1.8.4','deployment'],['payment-provider','External Payment Provider','external_api']].map(([id,name,kind]) => ({ id, name, kind: kind as GraphNodeKind, metadata: {} }))); for (const [from,to,relation] of [['payment-api','postgresql','depends_on'],['payment-api','redis','depends_on'],['payment-api','payment-worker','calls'],['payment-api','deployment-1.8.4','deployed_by'],['payment-api','payment-provider','calls'],['payment-worker','redis','depends_on']] as GraphEdge['relation'][][]) g.addEdge({ from, to, relation, metadata: {} }); return g; }
